server {
    listen 80;
    server_name _;
    client_max_body_size 20M;

    resolver 127.0.0.11 valid=10s ipv6=off;

    root /var/www/html/public;
    index index.php;

    location /api {
        set $backend_fcgi backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass $backend_fcgi;
    }

    location /sanctum {
        set $backend_fcgi backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass $backend_fcgi;
    }

    location /remote {
        set $backend_fcgi backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass $backend_fcgi;
    }

    location /up {
        set $backend_fcgi backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass $backend_fcgi;
    }

    location / {
        set $frontend_upstream http://frontend:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $frontend_upstream;
    }
}
